Added user with possix attribute.
freeipa/freeipa-pr-ci pull request #480
Opened 2022-09-14 07:40 UTC by amore17

For RFE Aduser is required with possix attribute.
Where users uid and gid is same.

Signed-off-by: Anuja More <amore@redhat.com>

2022-09-19 13:53 UTC, f-trivino requested changes
I would also add more details to the commit message.

2022-09-27 14:19 UTC, amore17 commented
Tested in : https://github.com/amore17/freeipa/pull/14

2022-09-29 19:07 UTC, flo-renaud commented
@amore17 nitpick but the commit msg mentions possix (with 2 s) while it should be posix (single s).
Otherwise LGTM.
Can you update the page https://www.freeipa.org/page/V4/AD_configuration_for_testing with the new user/group? Thanks.

2022-09-30 08:38 UTC, amore17 commented
> @amore17 nitpick but the commit msg mentions possix (with 2 s) while it should be posix (single s). Otherwise LGTM. Can you update the page https://www.freeipa.org/page/V4/AD_configuration_for_testing with the new user/group? Thanks.

Page is updated https://www.freeipa.org/page/V4/AD_configuration_for_testing#On_forest_root_AD

2022-09-30 13:26 UTC, flo-renaud approved these changes
Thanks, ack

2022-09-30 16:15 UTC, merged

2022-09-30 16:17 UTC, netoarmando commented
Deployed to all runners.